### ISSUE TITLE
Incorrect ClusterIssuer for Traefik ingress controller

### ISSUE THREAD

**Issue by phantasia15** [epinio/helm-charts#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, currently the following default `ClusterIssuer` will be created:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
   ...
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
   ...
```

The above annotations will instruct traefik to create a *HTTPS-only* route at `/.well-known/acme-challenge/...`. 
This won't work as the acme challenge is done with a HTTP route. 
```
kubectl get certificate
NAME              READY   SECRET                AGE
dex-tls           False    dex-tls               106m
epinio            False    epinio-tls            106m
epinio-registry   True    epinio-registry-tls   106m
minio-cert        True    minio-tls             106m
```
 

### Expected Behavior

The annotations should be removed from the ingressTemplate.

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Epinio Version: 1
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```
